In [1]:
%load_ext lab_black

from puzzles import load

import re

import numpy as np

from tqdm import tqdm

import time

In [2]:
ingr = np.array(
    [re.findall(r"\-?\d+", x) for x in load(15).strip().split("\n")]
).astype(int)

In [3]:
part1 = ingr[:, :-1]
part1

array([[ 4, -2,  0,  0],
       [ 0,  5, -1,  0],
       [-1,  0,  5,  0],
       [ 0,  0, -2,  2]])

In [4]:
def get_score(x):
    ns = np.reshape([*x, 100 - x.sum()], (4, 1)).astype(int)
    a = (part1 * ns).sum(0)
    a[a < 0] = 0
    return a.prod()

In [26]:
start = time.time()

best_score = -1e9
for i in tqdm(range(100)):
    for j in range(100):
        for k in range(100):
            l = 100 - (i + j + k)
            if l < 0:
                continue
            score = get_score(x=np.array([i, j, k]))
            if score > best_score:
                best_parts = [i, j, k]
                best_score = score

print(f"Time taken: {time.time() - start} s")

best_score, best_parts

100%|█████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:05<00:00, 17.56it/s]

Time taken: 5.70150899887085 s


(18965440, [24, 29, 31])

---

In [27]:
part2 = ingr
part2

array([[ 4, -2,  0,  0,  5],
       [ 0,  5, -1,  0,  8],
       [-1,  0,  5,  0,  6],
       [ 0,  0, -2,  2,  1]])

In [34]:
def get_score_and_calories(x):
    ns = np.reshape([*x, 100 - x.sum()], (4, 1)).astype(int)
    a = (part2[:, :-1] * ns).sum(0)
    a[a < 0] = 0
    return a.prod(), (part2[:, -1:] * ns).sum()

In [29]:
start = time.time()

best_score = -1e9
for i in tqdm(range(100)):
    for j in range(100):
        for k in range(100):
            l = 100 - (i + j + k)
            if l < 0:
                continue
            score, calories = get_score_and_calories(x=np.array([i, j, k]))
            if calories != 500:
                continue
            if score > best_score:
                best_parts = [i, j, k]
                best_score = score

print(f"Time taken: {time.time() - start} s")

best_score, best_parts

100%|█████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:07<00:00, 13.41it/s]

Time taken: 7.4651939868927 s


(15862900, [21, 23, 31])

---

https://habr.com/ru/company/ods/blog/448054/

In [8]:
from scipy.optimize import minimize


def neg_score(x):
    s = get_score(x)
    return -s


start = time.time()

res = minimize(
    neg_score,
    x0=np.array([25, 25, 25]),
    method="powell",
    options={"xtol": 1e-9, "disp": True},
)

print(res.x)

near = res.x.astype(int)
print(near)

best_score = 1e-9

for i in range(near[0] - 5, near[0] + 6):
    for j in range(near[1] - 5, near[1] + 6):
        for k in range(near[2] - 5, near[2] + 6):
            l = 100 - (i + j + k)
            score = get_score(x=np.array([i, j, k]))
            if score > best_score:
                best_parts = [i, j, k]
                best_score = score

print()
print(f"Time taken: {time.time() - start:.3f} s")

best_score, best_parts

Optimization terminated successfully.
         Current function value: -18157568.000000
         Iterations: 5
         Function evaluations: 698
[23.19616322 30.0764372  30.00000091]
[23 30 30]

Time taken: 0.230 s


(18965440, [24, 29, 31])

In [7]:
from scipy.optimize import minimize


def neg_score(x):
    s = get_score(x)
    return -s


start = time.time()

res = minimize(
    neg_score,
    x0=np.array([25, 5, 60]),
    method="powell",
    options={"xtol": 1e-9, "disp": True},
)

print(res.x)

near = res.x.astype(int)
print(near)

best_score = 1e-9

for i in range(near[0] - 5, near[0] + 6):
    for j in range(near[1] - 5, near[1] + 6):
        for k in range(near[2] - 5, near[2] + 6):
            l = 100 - (i + j + k)
            score = get_score(x=np.array([i, j, k]))
            if score > best_score:
                best_parts = [i, j, k]
                best_score = score

print()
print(f"Time taken: {time.time() - start:.3f} s")

best_score, best_parts

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 1
         Function evaluations: 109
[27.61803372  7.61803372 62.61803372]
[27  7 62]

Time taken: 0.101 s


(2276640, [22, 12, 57])