In [10]:
%load_ext lab_black

from puzzles import load

import numpy as np
import re

The lab_black extension is already loaded. To reload it, use:
  %reload_ext lab_black


In [11]:
s = load(14)

In [57]:
deers = np.array([re.findall(r"\d+", x) for x in s.strip().split("\n")]).astype(int)
deers

array([[ 22,   8, 165],
       [  8,  17, 114],
       [ 18,   6, 103],
       [ 25,   6, 145],
       [ 11,  12, 125],
       [ 21,   6, 121],
       [ 18,   3,  50],
       [ 20,   4,  75],
       [  7,  20, 119]])

In [58]:
T = 2503

In [59]:
S = deers[:, 1] * deers[:, 0]
S

array([176, 136, 108, 150, 132, 126,  54,  80, 140])

In [60]:
Ts = deers[:, 1] + deers[:, 2]
Ts

array([173, 131, 109, 151, 137, 127,  53,  79, 139])

In [61]:
N_ts = T // Ts
N_ts

array([14, 19, 22, 16, 18, 19, 47, 31, 18])

In [62]:
Rs = np.array([T - N_ts * Ts, deers[:, 1]]).min(axis=0) * deers[:, 0]
(N_ts * S + Rs).max()

2696

---

In [65]:
import pandas as pd

from tqdm import tqdm

In [376]:
df = pd.DataFrame(deers, columns=["v", "t_run", "t_rest"])

df["is_running"] = 1
df["t_run_left"] = df["t_run"]
df["t_rest_left"] = df["t_rest"]

df["traveled"] = 0
df["score"] = 0

for t in tqdm(range(T)):
    running = df["is_running"] == 1
    resting = df["is_running"] == 0

    df.loc[running, "traveled"] += df.loc[running, "v"]
    df.loc[running, "t_run_left"] -= 1

    tired = (df["t_run_left"] == 0) & running
    df.loc[tired, "is_running"] = 0
    df.loc[tired, "t_rest_left"] = df.loc[tired, "t_rest"]

    df.loc[resting, "t_rest_left"] -= 1

    ready = (df["t_rest_left"] == 0) & resting
    df.loc[ready, "is_running"] = 1
    df.loc[ready, "t_run_left"] = df.loc[ready, "t_run"]

    df.loc[df["traveled"] == df["traveled"].max(), "score"] += 1

100%|██████████████████████████████████████████████████████████████████████████████████████| 2503/2503 [00:18<00:00, 135.57it/s]


In [377]:
df["score"].max()

1084