In [1]:
%load_ext lab_black
%load_ext autoreload
%autoreload 2

from puzzles import load, load_tokens

In [2]:
N = int(load(19).strip())
N

3001330

In [3]:
from typing import Tuple

In [4]:
from functools import lru_cache

In [5]:
@lru_cache(maxsize=int(3e6))
def get_last(group_size: int, index: int) -> Tuple[Tuple, int]:
    a = list(range(group_size))
    if index == group_size - 1:
        return tuple(a[1:]), 0
    first, rest = a[:index], a[index:]
    is_zero = len(rest) % 2 == 0
    d = tuple(first + rest[::2])
    return d, len(d) - 1 if not is_zero else 0  #

In [6]:
print(get_last(2, 0))

((0,), 0)


In [7]:
print(get_last(2, 1))

((1,), 0)


In [8]:
print(get_last(3, 0))

((0, 2), 1)


In [9]:
print(get_last(3, 1))

((0, 1), 0)


In [10]:
print(get_last(3, 2))

((1, 2), 0)


In [11]:
def get_the_very_last(group_size: int, index: int = 0) -> int:
    t, index = get_last(group_size, index)
    while len(t) != 1:
        t_new, index = get_last(len(t), index)
        t = tuple(t[x] for x in t_new)
    return t[0] + 1

In [12]:
import time

In [13]:
t = time.perf_counter()
get_the_very_last(3001330)
print(f"took {time.perf_counter() - t:.4f}")

took 1.0053


---

In [23]:
import numpy as np

In [24]:
def find(group_size: int, i: int = 0):
    a = list([x + 1 for x in range(group_size)])
    while len(a) != 1:
        hc = len(a) // 2
        d = (i + hc) % len(a)
        x = a[i]
        del a[d]
        i = (a.index(x) + 1) % len(a)
    return a[0]

In [90]:
def find(group_size: int, i: int = 0):
    m = np.ones(group_size, dtype=int)

    while m.sum() > 1:
        w = np.where(m)[0]
        print(w)
        d = (i + (len(w) - 1) // 2) % len(w)
        print("\t\t", i, ">", d)
        m[w[d]] = 0
        w = np.where(m)[0]
        i = w[(i + 1) % len(w)]
        print("\t\t", i)

    return np.where(m)

In [91]:
find(5)

[0 1 2 3 4]
		 0 > 2
		 1
[0 1 3 4]
		 1 > 2
		 4
[0 1 4]
		 4 > 2
		 1
[0 1]
		 1 > 1
		 0


(array([0]),)

In [60]:
m = np.ones(5)
m

array([1., 1., 1., 1., 1.])

In [ ]:
i = 0
w = np.where(m)[0]

w

d = (i + len(w) // 2) % len(w)
d

m[w[d]] = 0

w = np.where(m)[0]
w

i = w[(i + 1) % len(w)]
i

In [22]:
s = time.perf_counter()
f = find(50000)
e = time.perf_counter() - s
e

6.759941260999767

In [22]:
s = time.perf_counter()
f = find(50000)
e = time.perf_counter() - s
e

6.759941260999767